### PR TITLE
Add event support

### PR DESCRIPTION
**Pull request by mkobetic**
This PR adds the ability to post Events. Four event types are supported: info, success, warning, error. An event must have a title and text. If client Namespace is set it is used as the event source.

This PR changes client.Namespace slightly, the trailing dot should not be included anymore. It is added automatically when needed.

/cc @snormore

### CODE REVIEW

**Comment by mkobetic** [comment]
An alternative to the Namespace change is to have Event() scan the Namespace string every time, and  only emit up to the first period. That's a bit of overhead but unlike metrics, event frequency shouldn't be terribly high anyway.

**Comment by mkobetic** [comment]
Thinking about it some more, it would probably be better to not mess with Namespace at this point. This package is used in a lot of places and this change would impact everybody. I'll make the change I proposed above.

**Comment by sidgopalan** [comment]
Thanks mkobetic. I've added a couple of comments to your commits. I'll merge this PR once those have been addressed.

**Comment by andrei-m** [comment]
Event support in this library would be awesome! @mkobetic I can try to address the code review comments if you're busy?

**Comment by mkobetic** [comment]
@andrei-m, feel free. I like the AlertType suggestion, I'm not sure about exposing all the other possible parameters (Does the metric API expose everything?), but a few more wouldn't hurt. I'm not sure I like packaging them as a struct either. I get that it would cut down on the number of required call parameters, but creating struct literal adds noise to the function call as well. I guess if it was a struct pointer, you could  just use nil if you're happy with the defaults. But this is just a quick brain-dump, I'm fine being out-voted on any of these :-).

**Comment by mkobetic** [comment]
Oh, regarding the hostname specifically, it seems the agent generally takes care of that. I'm not sure there are many cases when you'd want to override that. So that seems to me like a good candidate to leave out.

**Comment by andrei-m** [comment]
Thank you for the context. I'm going to work on this over the next couple of days.

**Comment by mkobetic** [comment]
Great! Thank you for helping.

**Pull request merged**
